earnings:
  calendar:
    ics_path: "calendar.ics"
    relcalid: "earnings.calendar.earnings"
    name: "Earnings Calendar"
    description: "Earnings dates for selected tickers."
    retention_years: 1
  tickers:
    [
      "INTC",
      "MSFT",
      "BABA",
      "GOOGL",
      "AMZN",
      "NVDA",
      "TSM",
      "TSLA",
      "AMD",
      "QCOM",
      "AAPL",
      "META",
      "KO",
      "BRK.B",
      "NVO",
      "SPCX",
      "RKLB",
      "OKLO",
      "HSAI",
    ]
  days_ahead: 60
  days_past: 10
